"""命令处理器可访问的强类型端口。"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from ..permissions import Mode
from ..sessions import SessionInfo

if TYPE_CHECKING:
    from .models import McpServerInfo, SandboxStatus


class CommandUI(Protocol):
    def println(self, message: str) -> None: ...

    def error(self, message: str) -> None: ...

    def request_exit(self) -> None: ...


class SessionCommands(Protocol):
    def mode(self) -> Mode: ...

    def set_mode(self, mode: Mode) -> None: ...

    def idle(self) -> bool: ...

    def submit_prompt(self, label: str, prompt: str) -> None: ...

    def force_compact(self) -> None: ...

    def open_resume(self) -> None: ...

    def clear_session(self) -> None: ...

    def resume_by_id(self, session_id: str) -> bool: ...

    def delete_session(self, session_id: str) -> bool: ...

    def clear_memory(self) -> None: ...


class SkillCommands(Protocol):
    def list_skills(self) -> list[tuple[str, str, str]]: ...

    def skill_info(self, name: str) -> str | None: ...

    def reload_skills(self) -> None: ...

    async def invoke_skill(self, name: str, args: str) -> None: ...


class StatusQueries(Protocol):
    def usage(self) -> tuple[int, int]: ...

    def model_name(self) -> str: ...

    def cwd(self) -> str: ...

    def tool_count(self) -> int: ...

    def memory_files(self) -> list[str]: ...

    def session_path(self) -> str: ...

    def session_id(self) -> str: ...

    def session_list(self) -> list[SessionInfo]: ...

    def memory_dirs(self) -> tuple[str, str]: ...

    def mcp_server_status(self) -> list[McpServerInfo]: ...


class SandboxCommands(Protocol):
    def status(self) -> SandboxStatus: ...

    def enable(self, auto_allow: bool) -> str | None: ...

    def disable(self) -> None: ...


class WorktreeCommands(Protocol):
    async def create_worktree(self, slug: str) -> str: ...

    def list_worktrees(self) -> list[tuple[str, str, str, bool]]: ...

    async def enter_worktree(self, slug: str) -> str: ...

    async def exit_worktree(self, *, remove: bool, discard: bool) -> str: ...

    async def remove_worktree(self, slug: str, *, discard: bool) -> str: ...
